# Generated by Django 4.2.6 on 2023-10-11 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('release_date', models.DateField()),
                ('cover', models.ImageField(upload_to='images/')),
                ('raiting', models.DecimalField(decimal_places=1, max_digits=2)),
            ],
        ),
    ]
